### PR TITLE
Thank you!

### PR DESCRIPTION
**Pull request by kikoseijo**
Good job here, 
just providing some tips, for people to figure it out themselves.

### CODE REVIEW

**Comment by kevupton** [comment]
Glad you like it :smiley:

**Comment by kevupton** [comment]
@kikoseijo 
You may like this as well: [auto-swagger-ui](https://github.com/kevupton/auto-swagger-ui)
I use it. 
Makes it easy to run the swagger ui on an api server. Automatically creates endpoints and hosts the files + the json for you. 
It by default uses this package to generate the swagger json.

**Comment by kikoseijo** [comment]
Just seen it, been playing with swagger + lumen for couple days now.
have used darkaonline/swagger-lume
But I just don't like annotations, trying to make yours work dynamically,  seems much better.
I quite like yours, 


There is a posible compatibility problem on your instructions here, because the Json Trait from Ethereal has also defined a $response.

```
public static $tag = "ChatMessages controller";
public static $summary = "This endpoints to serve all ChatMessages related endpoints.";
public static $responseDef = "#/definitions/Response";
```

as you see, I swapped for $responseDef, just for your knowledge.

Keep it up, you doing great contribution here.

**Comment by kevupton** [comment]
Ahh yeh of course. I will update the docs, and also I think I will do an update on eth. Make it a bit nicer.

**Pull request merged**
